mv /sdcard/tencent
mv /sdcard/Android/data/com.tencent.ig/cache
mv /sdcard/Android/data/com.tencent.ig/files/tbslog
mv /sdcard/Android/data/com.tencent.ig/files/cacheFile.txt
mv /sdcard/Android/data/com.tencent.ig/files/login-identifier.txt
mv /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
mv /sdcard/tencent
mv /sdcard/Android/data/com.tencent.ig/cache
mv /sdcard/Android/data/com.tencent.ig/files/tbslog
mv /sdcard/Android/data/com.tencent.ig/files/cacheFile.txt
mv /sdcard/Android/data/com.tencent.ig/files/login-identifier.txt
mv /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
mv /sdcard/tencent
mv /sdcard/Android/data/com.tencent.ig/cache
mv /sdcard/Android/data/com.tencent.ig/files/tbslog
mv /sdcard/Android/data/com.tencent.ig/files/cacheFile.txt
mv /sdcard/Android/data/com.tencent.ig/files/login-identifier.txt
mv /sdcard/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs